apiVersion: v1
kind: Service
metadata:
  labels:
    app: iotapp-nr2
  name: iotapp-nr2
spec:
  ports:
    - name: "1881"
      port: 1881
      targetPort: 1880
  externalIPs:
    - 10.1.0.4
  selector:
    app: iotapp-nr2
