apiVersion: v1
kind: Service
metadata:
  labels:
    app: nifi
  name: nifi
spec:
  ports:
    - name: "9090"
      port: 9090
      targetPort: 8080
    - name: "1030"
      port: 1030
      targetPort: 1030
  externalIPs:
    - 10.1.0.4
  selector:
    app: nifi
