apiVersion: v1
kind: Service
metadata:
  labels:
    app: personaldata
  name: personaldata
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: personaldata
