apiVersion: v1
kind: Service
metadata:
  labels:
    app: virtuoso-kb
  name: virtuoso-kb
spec:
  ports:
    - name: "8890"
      port: 8890
      targetPort: 8890
    - name: "1111"
      port: 1111
      targetPort: 1111
  externalIPs:
    - 10.1.0.4
  selector:
    app: virtuoso-kb
