apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kibana
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  strategy: {}
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - image: kibana:6.8.5
          name: kibana
          ports:
            - containerPort: 5601
          resources: {}
      restartPolicy: Always
