apiVersion: v1
kind: PersistentVolume
metadata:
  name: virtuoso-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ironstonevmmaster/virtuoso-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: virtuoso-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

