apiVersion: v1
kind: PersistentVolume
metadata:
  name: cv-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 12Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/my_nfs_volumes/cv_data"

