apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
  name: mongo
spec:
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  externalIPs:
    - 10.1.0.4
  selector:
    app: mongo
