apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - image: mongo:3.6
          ports:
            - containerPort: 27017
          name: mongo
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-storage
      restartPolicy: Always
      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: mongodb-pv-claim
